### PR TITLE
Load TextDoamin While Over php 5.3 in wp-mail-smtp.php

### PR DESCRIPTION
**Pull request by bestony**
Load TextDoamin While Over php 5.3 in wp-mail-smtp.php

## Description

I use PHP 7.1 for WordPress, and i made a language file but i can't load the language file. So, I read the code, and find the a if function to choose another file for site which use php over 5.3.

I copy the loadtextdomain code from wp_mail_smtp.php to wp-mail-smtp.php file. 

## Testing procedure

I add this code, and my language file can load for user.

## Screenshots (if appropriate):

image

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (modification of the currently available functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code has appropriate phpdoc comments with a description, `@since`, `@params` and `@return`.
- [x] My code is tested for both new installs and for users that are upgrading from older versions.

### CODE REVIEW

**Comment by bestony** [comment]
https://github.com/awesomemotive/wp-mail-smtp/issues/123

**Comment by slaFFik** [comment]
Hi, thanks for the PR.

I think this change won't be implemented. It's an extra headache to maintain translations in a plugin directory. It also increases the plugin size, and a vast majority of users won't need translations to other languages shipped with a plugin.
WordPress by default loads translations from `/wp-content/languages/plugins/` directory, if a translation in `.mo` file exist there for a plugin. So just move your file there.
By submitting your translation to https://translate.wordpress.org/projects/wp-plugins/wp-mail-smtp all Chinese plugin users will benefit, as this (or updated and maintained) translation will appear for all of them.

Pinging @jaredatch  to get his thoughts about this.

**Comment by bestony** [comment]
@slaFFik in your code, You include another file and return true this file. https://github.com/awesomemotive/wp-mail-smtp/blob/develop/wp_mail_smtp.php#L51 . Although you have the code in  https://github.com/awesomemotive/wp-mail-smtp/blob/develop/wp_mail_smtp.php#L856 ,but this code only use for php version lower or equal 5.3, if your php version over 7,  Plugin autoload wp-mail-smtp.php, In this file , No  load_plugin_textdomain called.

**Comment by bestony** [comment]
here is your code logic
image

**Comment by slaFFik** [comment]
@bestony Yes, PHP 5.2 code is left as is from 0.11.2 version of a plugin for backward compatibility, it won't be changed. New code, for PHP 5.3, doesn't require `load_plugin_textdomain()` as it's done on a WordPress level by taking translation from translate.wordpress.org and saving to a path written above.. I think, we will remove `/languages` directory as obsolete.

**Comment by bestony** [comment]
Oh,Sorry, I don't know the new feature of WordPress Level translation. 

but, remove the `/languages` isn't a good idea, there are many people use php lower 5.3.

I think the better way is you add a logic to detect is this plugin have a translation by wordpress ,if not , use load text domain function load language file manually.

it will more comfortable for every user.

> You know ,China Gov block the wordpress.com ,and wordpress.org be implicated.

**Comment by bestony** [comment]
Wow, I found the feature description https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#loading-text-domain :)

but , if you want to use this feature ,you need change  [Requires at least: 3.6](https://github.com/awesomemotive/wp-mail-smtp/blob/95b83a3c405b98017edb0d55ff3215b69cb69982/readme.txt#L4) to 4.6

**Comment by slaFFik** [comment]
So, to sum all of my investigations:
- we do have a code since 1.0 to load translations from plugin `/languages` directory
- that code was trying to do that from a wrong directory
- thus all `.mo` files were not loaded properly from plugin `/languages` directory
- but all translation were properly downloaded from translate.wp.org and loaded from there without issues.

I'm NOT merging this PR, as we had a code to load, it was just broken. And I don't want to introduce a logic outside of `/src` directory.

@bestony 
Thank you for bringing this issue up. Fixed in 1.2.5 of a plugin.

**Pull request closed without merging**
