### PR TITLE
Issue/70 - SMTPAutoTLS

### PR DESCRIPTION
**Pull request by jaredatch**

### CODE REVIEW

**Comment by jaredatch** [comment]
I've added the UI for that, but I'll let you @slaFFik handle the adjustments in `Options.php` since I'm less familiar with that right now :)

**Comment by jaredatch** [comment]
Right now the option is "Disable Auto TLS".

Another consideration would be to name this option "Auto TLS" which has the default setting of ON. Not sure if that would be 1) less confusing 2) more complicated to implement

Either way, really.

**Comment by jaredatch** [comment]
@slaFFik ok added an upgrade routine. Similar to what we do in WPF. See what you think.

Testing and I believe it works.

**Comment by slaFFik** [comment]
@jaredatch Works good in my tests.

**Pull request merged**
