### PR TITLE
Other SMTP mailer: Use method that retrieves defined constant options.

### LINKED ISSUE #27: Test page doesn't work when using defined constants and Other SMTP mailer
When I view this plugin's setting page, I see all the right settings (greyed out). But when I click over to this plugin's test page, the plugin reports that I don't have the sending method configured and that it can't send a test.

I've got a multisite install, am using this plugin version 1.4.1 network-activated and have defined all config items in wp-config.php. I'm using the Other SMTP mailer. 

## Plugin version 
1.4.1

## Current Behavior
The test page reports "You cannot send an email. Mailer is not properly configured. Please check your settings." and the Send Email button is greyed out.

## Expected Behavior
No error displayed, and I should be able to send the test email.

## Possible Solution
There is a bug preventing defined constants from being read in this situation. The bug is in one of these locations:
WPMailSMTP\Providers\SMTP\Mailer::is_mailer_complete()
or
WPMailSMTP\Options::get_group()

I was able to resolve the issue by changing is_mailer_complete() to use get(), which does inspect defined constants, instead of get_group(), which does not. I don't see any other usages of get_group() for the Other SMTP mailer, so this was the only change that was needed for my use case.

Here is the complete method code per my modifications:
`

	public function is_mailer_complete() {

		// Host and Port are the only really required options.
		if (
			! empty( $this->options->get($this->mailer, 'host') ) &&
			! empty( $this->options->get($this->mailer, 'port') )
		) {
			return true;
		}

		return false;
	}

`

## Steps to Reproduce (for bugs)
Here are the defined constants in my wp-config.php (with specific account details replaced as XXX). They are the same as commented in wp_mail_smtp.php:

define( 'WPMS_ON', true ); // True turns on the whole constants support and usage, false turns it off.
define( 'WPMS_MAIL_FROM', 'XXX' );
define( 'WPMS_MAIL_FROM_FORCE', true ); // True turns it on, false turns it off.
define( 'WPMS_MAIL_FROM_NAME', 'XXX' );
define( 'WPMS_MAIL_FROM_NAME_FORCE', true ); // True turns it on, false turns it off.
define( 'WPMS_MAILER', 'smtp' ); // Possible values: 'mail', 'gmail', 'mailgun', 'sendgrid', 'smtp'.
define( 'WPMS_SET_RETURN_PATH', true ); // Sets $phpmailer->Sender if true.
define( 'WPMS_SMTP_HOST', 'smtp.mandrillapp.com' ); // The SMTP mail host.
define( 'WPMS_SMTP_PORT', 587 ); // The SMTP server port number.
define( 'WPMS_SSL', 'tls' ); // Possible values '', 'ssl', 'tls' - note TLS is not STARTTLS.
define( 'WPMS_SMTP_AUTH', true ); // True turns it on, false turns it off.
define( 'WPMS_SMTP_USER', 'XXX' ); // SMTP authentication username, only used if WPMS_SMTP_AUTH is true.
define( 'WPMS_SMTP_PASS', 'XXX' ); // SMTP authentication password, only used if WPMS_SMTP_AUTH is true.
define( 'WPMS_SMTP_AUTOTLS', true ); // True turns it on, false turns it off.

### PR DESCRIPTION
**Pull request by jacobischwartz**
Fixes https://github.com/awesomemotive/WP-Mail-SMTP/issues/27

### CODE REVIEW

**Comment by lkraav** [comment]
@jacobischwartz thanks for the effort here, but the PR could certainly be easily modified to fit this plugin's code style better. Do you think you could figure it out?

**Comment by jacobischwartz** [comment]
@lkraav do you have the ability to accept this PR?

**Comment by lkraav** [comment]
I do not, but I can see how this PR is not going to pass just because of code style problems alone.

**Comment by jacobischwartz** [comment]
To be honest, I don't think it's worth my effort given the lack of attention from contributors. You're welcome to commit a reformat if you want.

**Comment by lkraav** [comment]
I just switched to Post SMTP myself, so not motivated either. Constant-configured WP Mail SMTP simply stopped sending multisite SMTP mails at one point (that's how I got here), no errors visible anywhere while WP Mail Log collected everything (so upstream is fine). I just don't have time to do in-depth debugging right now, so switched to Post SMTP - everything works fine, just doesn't have centralized multisite configuration.

Feeling like there's still room for a plugin that does ONLY SMTP, and doesnt complicate its codebase and UI with all the other mailer APIs. Maybe even no UI, just constant-based configuration. I could really use something that I can rely on not to break due to some updates to some other low-importance feature.

**Comment by slaFFik** [comment]
@jacobischwartz, thank you for the PR.

@lkraav is correct, I can't merge it as is because of the broken Code Style.
But the fix of that issue will land into plugin core in the next release.

Also, one more thing: the ideal PR is to fix the `Options::get_group()` method, instead of removing its usage. That's how I would personally proceed.

**Comment by spenserhale** [comment]
@slaFFik I wrote a PR that fixes the Options::get_group() method instead - #35. If you could please review. I had a question since Options::get_group() and Options::get_all() used different styles which once should plugin go forward with.

**Comment by slaFFik** [comment]
@spenserhale Reviewed it, thank you!

**Comment by slaFFik** [comment]
As `Options::get_group()` will be improved, I'm closing this PR.

**Pull request closed without merging**
